import = ["/Users/christoff/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[font.normal]
family = "Iosevka NF"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
blur = true
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.padding]
x = 12
y = 12
